azureEventHub:
  connectionString: "" # "Endpoint=sb://<namespace>.servicebus.windows.net/;SharedAccessKeyName=<keyname>;SharedAccessKey=<key>;EntityPath=<hubname>"

entityCount: 5  # Formerly nmbOfDevices
idKeyName: "device_Id"
maxMessages: 5 # Maximum number of messages per entity
delay: 1         # Delay in seconds

timestamp:
  enabled: true

geosection:
  type: square   # Geosection type: 'square', 'round', or 'none'
  center:
    lat: 0.0       # Latitude of the center (only for 'round' type)
    lon: 0.0       # Longitude of the center (only for 'round' type)
  bounds:
    radius: 1      # Radius, km (only for 'round' type)
    lat_range: [48.1850, 48.1890]  # Latitude range (only for 'square' type)
    lon_range: [16.40000, 16.407]  # Longitude range (only for 'square' type)

values:
  - name: "Temperature"
    min: 0
    max: 90
    type: "int"
  - name: "Size"
    min: 5
    max: 15
    type: "float"
